spring.application.name=kanvra-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/kanvra
spring.datasource.username=kanvra
spring.datasource.password=kanvra_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true